### PR TITLE
Fix hydration errors (#462)

### LINKED ISSUE #462: Fresh install has Hydration errors
## Current behavior

Getting following error while accessing the application

[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.
Header tabs are not rendering properly

## Steps to reproduce the issue

Do the fresh installation

## Can you handle fixing this bug by yourself?

- [X] YES
- [ ] NO

## Environment details

- Browser: Firefox 80.0 (64-bit)
- OS: MacOS Catalina 
- Code Version: master

## Additional information

This similar issue reported in vue-storefront as well  by @SethKitchen  
https://github.com/DivanteLtd/vue-storefront/issues/4773

### PR DESCRIPTION
**Pull request by dixitdeepak**
### Related Issues

Closes #462 

### Short Description and Why It's Useful

 Fresh install has Hydration errors, its due to vue version mismatch in capybara theme, I did not get a chance to dig into more why this was failing. It might be due to recent vue release [1] , in this release serialize-javascript dependecy updated from 2.1.2 to 3.1.0

[1] https://github.com/vuejs/vue/releases/tag/v2.6.12
https://github.com/yahoo/serialize-javascript/releases/tag/v3.0.0
https://github.com/yahoo/serialize-javascript/releases/tag/v3.1.0

### Screenshots of Visual Changes before/after (If There Are Any)

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance

- [ ] I read and followed [contribution rules](https://github.com/DivanteLtd/vsf-capybara/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Review by andres-linares2211 — APPROVED** [review]
Works perfectly!

**Comment by dixitdeepak** [comment]
@Fifciu can we review and accept this PR?
Too many users facing similar issue

**Comment by dixitdeepak** [comment]
Thanks @Fifciu

**Comment by YannisMarios** [comment]
This error still exists as of 03/01/2021 on a fresh install

**Pull request merged**
