### PR TITLE
Fixed console warning rleated to Value of key 'Sort by' is not a string #467

### PR DESCRIPTION
**Pull request by dixitdeepak**
### Related Issues

Closes #475

### Short Description and Why It's Useful

Fixed console warning rleated to Value of key 'Sort by' is not a string

### Screenshots of Visual Changes before/after (If There Are Any)

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vsf-capybara/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Review by Fifciu — CHANGES_REQUESTED** [review]
Good catch! Please resolve conflict with Changelog and I can merge it then

**Comment by dixitdeepak** [comment]
@Fifciu Done.

I have some ideas to manage chagnelogs, so that we can't get conflicts on frequent basis
I'll post my idea on slack group.

**Review by Fifciu — APPROVED** [review]

**Comment by Fifciu** [comment]
These ideas on Slack look really well. We are discussing them internally :)

**Comment by dixitdeepak** [comment]
Thanks @Fifciu

**Pull request merged**
