### PR TITLE
#408 missing step installation

### LINKED ISSUE #408: Missing step to generate local.json file of vsf-capybara in the installation steps given
While following the steps for manual installation of vsf-capybara, I found that before step no. 4 we need to include one more step to first generate the local.json file of capybara.
I was able to generate the local.json file by running the command:
_node scripts/generate-local-config.js_

If everyone agrees, I would like to contribute this change in the documentation.

### PR DESCRIPTION
**Pull request by mohammad-k8**
### Related Issues

Closes #408 

### Short Description and Why It's Useful
Added the missing step to generate the local.json file.
This will be useful for new user when he/she tries to install vsf-capybara using manual installation steps given.

### Screenshots of Visual Changes before/after (If There Are Any)

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance

- [ ] I read and followed [contribution rules](https://github.com/DivanteLtd/vsf-capybara/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by mohammad-k8** [comment]
@psmyrek should I create a new PR and close this one to fix the CLA check?

**Comment by psmyrek** [comment]
@mohammad-k8 I think it's not needed to create new PR - please just sign CLA for this PR [here](https://cla-assistant.io/DivanteLtd/vsf-capybara?pullRequest=409).

**Comment by mohammad-k8** [comment]
> @mohammad-k8 I think it's not needed to create new PR - please just sign CLA for this PR [here](https://cla-assistant.io/DivanteLtd/vsf-capybara?pullRequest=409).

@psmyrek Already did it. Still showing that it's pending.

**Comment by psmyrek** [comment]
OK, I see where is the problem: to make CLA work properly you must use the same e-mail address you have used in the commit and in your GitHub account which you used to sign CLA.

So if you have it configured locally then please try `git push --force` to overwrite your PR and then please try sign CLA one more time.

**Comment by mohammad-k8** [comment]
> OK, I see where is the problem: to make CLA work properly you must use the same e-mail address you have used in the commit and in your GitHub account which you used to sign CLA.
> 
> So if you have it configured locally then please try `git push --force` to overwrite your PR and then please try sign CLA one more time.

@psmyrek I have tried everything. May be it was a problem while committing. My email address was not properly set at that time in git. I have it set correctly now and the problem is fixed in another PR created later on storefront-ui project.

**Comment by psmyrek** [comment]
Indeed, it was a problem at the time of commiting but doing `git push --force` now with all your changes from this PR (after you have proper e-mail address configured locally in your git) should fix it by overwriting PR history.

Anyway, if you have tried everything and it is still not working then please create a new PR and close this one.

**Pull request closed without merging**
